github:
  features:
    wiki: true
  description: "Apache EventMesh (Incubating) Website"
  homepage: https://eventmesh.apache.org

staging:
  profile: ~
  whoami: asf-site

publish:
  whoami: asf-site

notifications:
  commits:      commits@eventmesh.apache.org
  # Send all issue emails (new, closed, comments) to issues@
  issues:       issues@eventmesh.apache.org
  # Send new/closed PR notifications to dev@
  pullrequests_status: dev@eventmesh.apache.org
  # Send individual PR comments/reviews to issues@
  pullrequests_comment: issues@eventmesh.apache.org
  jira_options: link label worklog
